//Si units 
export const SI = {
    mass: "kg","Mass": "Kg",
    MassDefect: "kg",
    mass_A: "kg",
    mass_B: "kg",
    m1: "kg",
    m2: "kg",
    acceleration: "m/s²",
    velocity: "m/s","final Velocity": "m/s","Escape Velocity": "m/s",
    u1: "m/s",
    u2: "m/s",
    v1: "m/s",
    v2: "m/s",
    force: " N or Kg.m/s²",
    "Gravitational Force": " N or Kg.m/s²",
    distance:"m","Distance":"m", "Radius":"m",
    energy: "Joules","Energy Released": "Joules","Energy Potential Energy":"Joules",
    field: "N/Kg", "Gravitational Field" : "N/kg",
    area: "m²", "Area": "m²",
    time: "s", "Time": "s", "TimePeriod":"s","Time Period":"s",
    angular_momentum: "kg-m²/s", "Angular Momentum": "kg-m²/s",
    sma: "m", "Semi-major axis": "m", "a": "m",
  };